# Generated by Django 4.0.4 on 2023-08-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spanglish', '0005_alter_sentence_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spanglish.language'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spanglish.sentence'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spanglish.word'),
        ),
    ]
