# Generated by Django 4.0.4 on 2023-08-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanglish', '0007_translation_word_or_sentence'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='translation',
            name='word_or_sentence',
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.CheckConstraint(check=models.Q(('word__isnull', False), ('sentence__isnull', True)), name='word_or_sentence'),
        ),
    ]
