# Generated by Django 4.0.4 on 2023-08-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanglish', '0010_remove_translation_word_or_sentence'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.CheckConstraint(check=models.Q(('sentence__isnull', True), ('word__isnull', True)), name='word_or_sentence'),
        ),
    ]
