# Generated by Django 4.0.4 on 2023-08-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanglish', '0012_remove_translation_word_or_sentence_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='translation',
            name='word_or_sentence',
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.CheckConstraint(check=models.Q(('word__isnull', True), ('sentence__isnull', True)), name='word_or_sentence'),
        ),
    ]
