# Generated by Django 4.0.4 on 2023-08-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spanglish', '0016_remove_translation_word_or_sentence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbTense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='language', to='spanglish.language'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentence', to='spanglish.sentence'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word', to='spanglish.word'),
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yo', models.CharField(blank=True, max_length=25, null=True)),
                ('tu', models.CharField(blank=True, max_length=25, null=True)),
                ('usted', models.CharField(blank=True, max_length=25, null=True)),
                ('nosotros', models.CharField(blank=True, max_length=25, null=True)),
                ('vosotros', models.CharField(blank=True, max_length=25, null=True)),
                ('ustedes', models.CharField(blank=True, max_length=25, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('tense', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spanglish.verbtense')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spanglish.word')),
            ],
            options={
                'unique_together': {('tense', 'word')},
            },
        ),
    ]
