# Generated by Django 4.0.4 on 2023-11-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanglish', '0018_alter_verb_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbtense',
            name='name',
            field=models.CharField(choices=[('SIMPLE_PRESENT', 'EL PRESENTE SIMPLE'), ('SIMPLE_PAST', 'EL PASADO SIMPLE'), ('SIMPLE_FUTURE', 'EL FUTURO SIMPLE'), ('PRESENT_CONTINUOUS', 'EL PRESENTE CONTINUO'), ('PAST_CONTINUOUS', 'EL PASADO CONTINUO'), ('FUTURE_CONTINUOUS', 'EL FUTURO CONTINUO'), ('PRESENT_PERFECT', 'EL PRESENTE PERFECTO'), ('PAST_PERFECT', 'EL PASADO PERFECTO'), ('FUTURE_PERFECT', 'EL FUTURO PERFECTO'), ('PRESENT_PERFECT_CONTINUOUS', 'EL PRESENTE PERFECTO CONTINUO'), ('PAST_PERFECT_CONTINUOUS', 'EL PASADO PERFECTO CONTINUO'), ('FUTURE_PERFECT_CONTINUOUS', 'EL FUTURO PERFECTO CONTINUO')], max_length=50, unique=True),
        ),
    ]
